//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionWeb.Servicios.Colegio {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tbl_Estudiante", Namespace="http://schemas.datacontract.org/2004/07/Entidades")]
    [System.SerializableAttribute()]
    public partial class tbl_Estudiante : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string est_apellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string est_cedulaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int est_id_estudianteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string est_nombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string est_telefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AplicacionWeb.Servicios.Colegio.tbl_Asistencia[] tbl_AsistenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AplicacionWeb.Servicios.Colegio.tbl_Nota[] tbl_NotaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string est_apellidos {
            get {
                return this.est_apellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.est_apellidosField, value) != true)) {
                    this.est_apellidosField = value;
                    this.RaisePropertyChanged("est_apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string est_cedula {
            get {
                return this.est_cedulaField;
            }
            set {
                if ((object.ReferenceEquals(this.est_cedulaField, value) != true)) {
                    this.est_cedulaField = value;
                    this.RaisePropertyChanged("est_cedula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int est_id_estudiante {
            get {
                return this.est_id_estudianteField;
            }
            set {
                if ((this.est_id_estudianteField.Equals(value) != true)) {
                    this.est_id_estudianteField = value;
                    this.RaisePropertyChanged("est_id_estudiante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string est_nombres {
            get {
                return this.est_nombresField;
            }
            set {
                if ((object.ReferenceEquals(this.est_nombresField, value) != true)) {
                    this.est_nombresField = value;
                    this.RaisePropertyChanged("est_nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string est_telefono {
            get {
                return this.est_telefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.est_telefonoField, value) != true)) {
                    this.est_telefonoField = value;
                    this.RaisePropertyChanged("est_telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AplicacionWeb.Servicios.Colegio.tbl_Asistencia[] tbl_Asistencia {
            get {
                return this.tbl_AsistenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_AsistenciaField, value) != true)) {
                    this.tbl_AsistenciaField = value;
                    this.RaisePropertyChanged("tbl_Asistencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AplicacionWeb.Servicios.Colegio.tbl_Nota[] tbl_Nota {
            get {
                return this.tbl_NotaField;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_NotaField, value) != true)) {
                    this.tbl_NotaField = value;
                    this.RaisePropertyChanged("tbl_Nota");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tbl_Asistencia", Namespace="http://schemas.datacontract.org/2004/07/Entidades")]
    [System.SerializableAttribute()]
    public partial class tbl_Asistencia : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime asi_fecha_asistenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int asi_id_asistenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool asi_tomar_asistenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> cla_id_claseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> est_id_estudianteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AplicacionWeb.Servicios.Colegio.tbl_Clase tbl_ClaseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AplicacionWeb.Servicios.Colegio.tbl_Estudiante tbl_EstudianteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime asi_fecha_asistencia {
            get {
                return this.asi_fecha_asistenciaField;
            }
            set {
                if ((this.asi_fecha_asistenciaField.Equals(value) != true)) {
                    this.asi_fecha_asistenciaField = value;
                    this.RaisePropertyChanged("asi_fecha_asistencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int asi_id_asistencia {
            get {
                return this.asi_id_asistenciaField;
            }
            set {
                if ((this.asi_id_asistenciaField.Equals(value) != true)) {
                    this.asi_id_asistenciaField = value;
                    this.RaisePropertyChanged("asi_id_asistencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool asi_tomar_asistencia {
            get {
                return this.asi_tomar_asistenciaField;
            }
            set {
                if ((this.asi_tomar_asistenciaField.Equals(value) != true)) {
                    this.asi_tomar_asistenciaField = value;
                    this.RaisePropertyChanged("asi_tomar_asistencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> cla_id_clase {
            get {
                return this.cla_id_claseField;
            }
            set {
                if ((this.cla_id_claseField.Equals(value) != true)) {
                    this.cla_id_claseField = value;
                    this.RaisePropertyChanged("cla_id_clase");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> est_id_estudiante {
            get {
                return this.est_id_estudianteField;
            }
            set {
                if ((this.est_id_estudianteField.Equals(value) != true)) {
                    this.est_id_estudianteField = value;
                    this.RaisePropertyChanged("est_id_estudiante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AplicacionWeb.Servicios.Colegio.tbl_Clase tbl_Clase {
            get {
                return this.tbl_ClaseField;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_ClaseField, value) != true)) {
                    this.tbl_ClaseField = value;
                    this.RaisePropertyChanged("tbl_Clase");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AplicacionWeb.Servicios.Colegio.tbl_Estudiante tbl_Estudiante {
            get {
                return this.tbl_EstudianteField;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_EstudianteField, value) != true)) {
                    this.tbl_EstudianteField = value;
                    this.RaisePropertyChanged("tbl_Estudiante");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tbl_Nota", Namespace="http://schemas.datacontract.org/2004/07/Entidades")]
    [System.SerializableAttribute()]
    public partial class tbl_Nota : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> cla_id_claseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> est_id_estudianteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int not_id_notaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> not_nota1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> not_nota2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> not_nota3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> not_nota4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> qui_id_quimestreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AplicacionWeb.Servicios.Colegio.tbl_Clase tbl_ClaseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AplicacionWeb.Servicios.Colegio.tbl_Estudiante tbl_EstudianteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AplicacionWeb.Servicios.Colegio.tbl_Quimestre tbl_QuimestreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> cla_id_clase {
            get {
                return this.cla_id_claseField;
            }
            set {
                if ((this.cla_id_claseField.Equals(value) != true)) {
                    this.cla_id_claseField = value;
                    this.RaisePropertyChanged("cla_id_clase");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> est_id_estudiante {
            get {
                return this.est_id_estudianteField;
            }
            set {
                if ((this.est_id_estudianteField.Equals(value) != true)) {
                    this.est_id_estudianteField = value;
                    this.RaisePropertyChanged("est_id_estudiante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int not_id_nota {
            get {
                return this.not_id_notaField;
            }
            set {
                if ((this.not_id_notaField.Equals(value) != true)) {
                    this.not_id_notaField = value;
                    this.RaisePropertyChanged("not_id_nota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> not_nota1 {
            get {
                return this.not_nota1Field;
            }
            set {
                if ((this.not_nota1Field.Equals(value) != true)) {
                    this.not_nota1Field = value;
                    this.RaisePropertyChanged("not_nota1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> not_nota2 {
            get {
                return this.not_nota2Field;
            }
            set {
                if ((this.not_nota2Field.Equals(value) != true)) {
                    this.not_nota2Field = value;
                    this.RaisePropertyChanged("not_nota2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> not_nota3 {
            get {
                return this.not_nota3Field;
            }
            set {
                if ((this.not_nota3Field.Equals(value) != true)) {
                    this.not_nota3Field = value;
                    this.RaisePropertyChanged("not_nota3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> not_nota4 {
            get {
                return this.not_nota4Field;
            }
            set {
                if ((this.not_nota4Field.Equals(value) != true)) {
                    this.not_nota4Field = value;
                    this.RaisePropertyChanged("not_nota4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> qui_id_quimestre {
            get {
                return this.qui_id_quimestreField;
            }
            set {
                if ((this.qui_id_quimestreField.Equals(value) != true)) {
                    this.qui_id_quimestreField = value;
                    this.RaisePropertyChanged("qui_id_quimestre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AplicacionWeb.Servicios.Colegio.tbl_Clase tbl_Clase {
            get {
                return this.tbl_ClaseField;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_ClaseField, value) != true)) {
                    this.tbl_ClaseField = value;
                    this.RaisePropertyChanged("tbl_Clase");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AplicacionWeb.Servicios.Colegio.tbl_Estudiante tbl_Estudiante {
            get {
                return this.tbl_EstudianteField;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_EstudianteField, value) != true)) {
                    this.tbl_EstudianteField = value;
                    this.RaisePropertyChanged("tbl_Estudiante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AplicacionWeb.Servicios.Colegio.tbl_Quimestre tbl_Quimestre {
            get {
                return this.tbl_QuimestreField;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_QuimestreField, value) != true)) {
                    this.tbl_QuimestreField = value;
                    this.RaisePropertyChanged("tbl_Quimestre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tbl_Clase", Namespace="http://schemas.datacontract.org/2004/07/Entidades")]
    [System.SerializableAttribute()]
    public partial class tbl_Clase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int au_id_aulaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cla_id_claseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int doc_id_docenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int mat_id_materiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AplicacionWeb.Servicios.Colegio.tbl_Asistencia[] tbl_AsistenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AplicacionWeb.Servicios.Colegio.tbl_Aula tbl_AulaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AplicacionWeb.Servicios.Colegio.tbl_Docente tbl_DocenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AplicacionWeb.Servicios.Colegio.tbl_Materia tbl_MateriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AplicacionWeb.Servicios.Colegio.tbl_Nota[] tbl_NotaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int au_id_aula {
            get {
                return this.au_id_aulaField;
            }
            set {
                if ((this.au_id_aulaField.Equals(value) != true)) {
                    this.au_id_aulaField = value;
                    this.RaisePropertyChanged("au_id_aula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cla_id_clase {
            get {
                return this.cla_id_claseField;
            }
            set {
                if ((this.cla_id_claseField.Equals(value) != true)) {
                    this.cla_id_claseField = value;
                    this.RaisePropertyChanged("cla_id_clase");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int doc_id_docente {
            get {
                return this.doc_id_docenteField;
            }
            set {
                if ((this.doc_id_docenteField.Equals(value) != true)) {
                    this.doc_id_docenteField = value;
                    this.RaisePropertyChanged("doc_id_docente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int mat_id_materia {
            get {
                return this.mat_id_materiaField;
            }
            set {
                if ((this.mat_id_materiaField.Equals(value) != true)) {
                    this.mat_id_materiaField = value;
                    this.RaisePropertyChanged("mat_id_materia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AplicacionWeb.Servicios.Colegio.tbl_Asistencia[] tbl_Asistencia {
            get {
                return this.tbl_AsistenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_AsistenciaField, value) != true)) {
                    this.tbl_AsistenciaField = value;
                    this.RaisePropertyChanged("tbl_Asistencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AplicacionWeb.Servicios.Colegio.tbl_Aula tbl_Aula {
            get {
                return this.tbl_AulaField;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_AulaField, value) != true)) {
                    this.tbl_AulaField = value;
                    this.RaisePropertyChanged("tbl_Aula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AplicacionWeb.Servicios.Colegio.tbl_Docente tbl_Docente {
            get {
                return this.tbl_DocenteField;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_DocenteField, value) != true)) {
                    this.tbl_DocenteField = value;
                    this.RaisePropertyChanged("tbl_Docente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AplicacionWeb.Servicios.Colegio.tbl_Materia tbl_Materia {
            get {
                return this.tbl_MateriaField;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_MateriaField, value) != true)) {
                    this.tbl_MateriaField = value;
                    this.RaisePropertyChanged("tbl_Materia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AplicacionWeb.Servicios.Colegio.tbl_Nota[] tbl_Nota {
            get {
                return this.tbl_NotaField;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_NotaField, value) != true)) {
                    this.tbl_NotaField = value;
                    this.RaisePropertyChanged("tbl_Nota");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tbl_Aula", Namespace="http://schemas.datacontract.org/2004/07/Entidades")]
    [System.SerializableAttribute()]
    public partial class tbl_Aula : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int au_id_aulaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string au_nombre_aulaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AplicacionWeb.Servicios.Colegio.tbl_Clase[] tbl_ClaseField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int au_id_aula {
            get {
                return this.au_id_aulaField;
            }
            set {
                if ((this.au_id_aulaField.Equals(value) != true)) {
                    this.au_id_aulaField = value;
                    this.RaisePropertyChanged("au_id_aula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string au_nombre_aula {
            get {
                return this.au_nombre_aulaField;
            }
            set {
                if ((object.ReferenceEquals(this.au_nombre_aulaField, value) != true)) {
                    this.au_nombre_aulaField = value;
                    this.RaisePropertyChanged("au_nombre_aula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AplicacionWeb.Servicios.Colegio.tbl_Clase[] tbl_Clase {
            get {
                return this.tbl_ClaseField;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_ClaseField, value) != true)) {
                    this.tbl_ClaseField = value;
                    this.RaisePropertyChanged("tbl_Clase");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tbl_Docente", Namespace="http://schemas.datacontract.org/2004/07/Entidades")]
    [System.SerializableAttribute()]
    public partial class tbl_Docente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string doc_apellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string doc_cedulaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int doc_id_docenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string doc_nombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string doc_telefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AplicacionWeb.Servicios.Colegio.tbl_Clase[] tbl_ClaseField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string doc_apellidos {
            get {
                return this.doc_apellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.doc_apellidosField, value) != true)) {
                    this.doc_apellidosField = value;
                    this.RaisePropertyChanged("doc_apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string doc_cedula {
            get {
                return this.doc_cedulaField;
            }
            set {
                if ((object.ReferenceEquals(this.doc_cedulaField, value) != true)) {
                    this.doc_cedulaField = value;
                    this.RaisePropertyChanged("doc_cedula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int doc_id_docente {
            get {
                return this.doc_id_docenteField;
            }
            set {
                if ((this.doc_id_docenteField.Equals(value) != true)) {
                    this.doc_id_docenteField = value;
                    this.RaisePropertyChanged("doc_id_docente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string doc_nombres {
            get {
                return this.doc_nombresField;
            }
            set {
                if ((object.ReferenceEquals(this.doc_nombresField, value) != true)) {
                    this.doc_nombresField = value;
                    this.RaisePropertyChanged("doc_nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string doc_telefono {
            get {
                return this.doc_telefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.doc_telefonoField, value) != true)) {
                    this.doc_telefonoField = value;
                    this.RaisePropertyChanged("doc_telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AplicacionWeb.Servicios.Colegio.tbl_Clase[] tbl_Clase {
            get {
                return this.tbl_ClaseField;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_ClaseField, value) != true)) {
                    this.tbl_ClaseField = value;
                    this.RaisePropertyChanged("tbl_Clase");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tbl_Materia", Namespace="http://schemas.datacontract.org/2004/07/Entidades")]
    [System.SerializableAttribute()]
    public partial class tbl_Materia : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mat_cod_materiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int mat_id_materiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mat_nombre_materiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AplicacionWeb.Servicios.Colegio.tbl_Clase[] tbl_ClaseField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mat_cod_materia {
            get {
                return this.mat_cod_materiaField;
            }
            set {
                if ((object.ReferenceEquals(this.mat_cod_materiaField, value) != true)) {
                    this.mat_cod_materiaField = value;
                    this.RaisePropertyChanged("mat_cod_materia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int mat_id_materia {
            get {
                return this.mat_id_materiaField;
            }
            set {
                if ((this.mat_id_materiaField.Equals(value) != true)) {
                    this.mat_id_materiaField = value;
                    this.RaisePropertyChanged("mat_id_materia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mat_nombre_materia {
            get {
                return this.mat_nombre_materiaField;
            }
            set {
                if ((object.ReferenceEquals(this.mat_nombre_materiaField, value) != true)) {
                    this.mat_nombre_materiaField = value;
                    this.RaisePropertyChanged("mat_nombre_materia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AplicacionWeb.Servicios.Colegio.tbl_Clase[] tbl_Clase {
            get {
                return this.tbl_ClaseField;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_ClaseField, value) != true)) {
                    this.tbl_ClaseField = value;
                    this.RaisePropertyChanged("tbl_Clase");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tbl_Quimestre", Namespace="http://schemas.datacontract.org/2004/07/Entidades")]
    [System.SerializableAttribute()]
    public partial class tbl_Quimestre : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime qui_fecha_finField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime qui_fecha_inicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int qui_id_quimestreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string qui_numero_quimestreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AplicacionWeb.Servicios.Colegio.tbl_Nota[] tbl_NotaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime qui_fecha_fin {
            get {
                return this.qui_fecha_finField;
            }
            set {
                if ((this.qui_fecha_finField.Equals(value) != true)) {
                    this.qui_fecha_finField = value;
                    this.RaisePropertyChanged("qui_fecha_fin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime qui_fecha_inicio {
            get {
                return this.qui_fecha_inicioField;
            }
            set {
                if ((this.qui_fecha_inicioField.Equals(value) != true)) {
                    this.qui_fecha_inicioField = value;
                    this.RaisePropertyChanged("qui_fecha_inicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int qui_id_quimestre {
            get {
                return this.qui_id_quimestreField;
            }
            set {
                if ((this.qui_id_quimestreField.Equals(value) != true)) {
                    this.qui_id_quimestreField = value;
                    this.RaisePropertyChanged("qui_id_quimestre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string qui_numero_quimestre {
            get {
                return this.qui_numero_quimestreField;
            }
            set {
                if ((object.ReferenceEquals(this.qui_numero_quimestreField, value) != true)) {
                    this.qui_numero_quimestreField = value;
                    this.RaisePropertyChanged("qui_numero_quimestre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AplicacionWeb.Servicios.Colegio.tbl_Nota[] tbl_Nota {
            get {
                return this.tbl_NotaField;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_NotaField, value) != true)) {
                    this.tbl_NotaField = value;
                    this.RaisePropertyChanged("tbl_Nota");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="vta_Clase", Namespace="http://schemas.datacontract.org/2004/07/Entidades")]
    [System.SerializableAttribute()]
    public partial class vta_Clase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int au_id_aulaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string au_nombre_aulaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cla_id_claseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string doc_apellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int doc_id_docenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string doc_nombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int mat_id_materiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mat_nombre_materiaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int au_id_aula {
            get {
                return this.au_id_aulaField;
            }
            set {
                if ((this.au_id_aulaField.Equals(value) != true)) {
                    this.au_id_aulaField = value;
                    this.RaisePropertyChanged("au_id_aula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string au_nombre_aula {
            get {
                return this.au_nombre_aulaField;
            }
            set {
                if ((object.ReferenceEquals(this.au_nombre_aulaField, value) != true)) {
                    this.au_nombre_aulaField = value;
                    this.RaisePropertyChanged("au_nombre_aula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cla_id_clase {
            get {
                return this.cla_id_claseField;
            }
            set {
                if ((this.cla_id_claseField.Equals(value) != true)) {
                    this.cla_id_claseField = value;
                    this.RaisePropertyChanged("cla_id_clase");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string doc_apellidos {
            get {
                return this.doc_apellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.doc_apellidosField, value) != true)) {
                    this.doc_apellidosField = value;
                    this.RaisePropertyChanged("doc_apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int doc_id_docente {
            get {
                return this.doc_id_docenteField;
            }
            set {
                if ((this.doc_id_docenteField.Equals(value) != true)) {
                    this.doc_id_docenteField = value;
                    this.RaisePropertyChanged("doc_id_docente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string doc_nombres {
            get {
                return this.doc_nombresField;
            }
            set {
                if ((object.ReferenceEquals(this.doc_nombresField, value) != true)) {
                    this.doc_nombresField = value;
                    this.RaisePropertyChanged("doc_nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int mat_id_materia {
            get {
                return this.mat_id_materiaField;
            }
            set {
                if ((this.mat_id_materiaField.Equals(value) != true)) {
                    this.mat_id_materiaField = value;
                    this.RaisePropertyChanged("mat_id_materia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mat_nombre_materia {
            get {
                return this.mat_nombre_materiaField;
            }
            set {
                if ((object.ReferenceEquals(this.mat_nombre_materiaField, value) != true)) {
                    this.mat_nombre_materiaField = value;
                    this.RaisePropertyChanged("mat_nombre_materia");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tbl_user", Namespace="http://schemas.datacontract.org/2004/07/Entidades")]
    [System.SerializableAttribute()]
    public partial class tbl_user : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string contraseñaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreCuentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombrePersonaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tipoUsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string contraseña {
            get {
                return this.contraseñaField;
            }
            set {
                if ((object.ReferenceEquals(this.contraseñaField, value) != true)) {
                    this.contraseñaField = value;
                    this.RaisePropertyChanged("contraseña");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombreCuenta {
            get {
                return this.nombreCuentaField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreCuentaField, value) != true)) {
                    this.nombreCuentaField = value;
                    this.RaisePropertyChanged("nombreCuenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombrePersona {
            get {
                return this.nombrePersonaField;
            }
            set {
                if ((object.ReferenceEquals(this.nombrePersonaField, value) != true)) {
                    this.nombrePersonaField = value;
                    this.RaisePropertyChanged("nombrePersona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tipoUsuario {
            get {
                return this.tipoUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.tipoUsuarioField, value) != true)) {
                    this.tipoUsuarioField = value;
                    this.RaisePropertyChanged("tipoUsuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/WcfColegio")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Servicios.Colegio.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAlumnos", ReplyAction="http://tempuri.org/IService1/GetAlumnosResponse")]
        AplicacionWeb.Servicios.Colegio.tbl_Estudiante[] GetAlumnos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDocentes", ReplyAction="http://tempuri.org/IService1/GetDocentesResponse")]
        AplicacionWeb.Servicios.Colegio.tbl_Docente[] GetDocentes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetQuimestres", ReplyAction="http://tempuri.org/IService1/GetQuimestresResponse")]
        AplicacionWeb.Servicios.Colegio.tbl_Quimestre[] GetQuimestres();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAulas", ReplyAction="http://tempuri.org/IService1/GetAulasResponse")]
        AplicacionWeb.Servicios.Colegio.tbl_Aula[] GetAulas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMaterias", ReplyAction="http://tempuri.org/IService1/GetMateriasResponse")]
        AplicacionWeb.Servicios.Colegio.tbl_Materia[] GetMaterias();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetClases", ReplyAction="http://tempuri.org/IService1/GetClasesResponse")]
        AplicacionWeb.Servicios.Colegio.tbl_Clase[] GetClases();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAsistencias", ReplyAction="http://tempuri.org/IService1/GetAsistenciasResponse")]
        AplicacionWeb.Servicios.Colegio.tbl_Asistencia[] GetAsistencias();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetNotas", ReplyAction="http://tempuri.org/IService1/GetNotasResponse")]
        AplicacionWeb.Servicios.Colegio.tbl_Nota[] GetNotas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetVistaClases", ReplyAction="http://tempuri.org/IService1/GetVistaClasesResponse")]
        AplicacionWeb.Servicios.Colegio.vta_Clase[] GetVistaClases();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertAlumno", ReplyAction="http://tempuri.org/IService1/InsertAlumnoResponse")]
        void InsertAlumno(AplicacionWeb.Servicios.Colegio.tbl_Estudiante nuevoAlumno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertDocente", ReplyAction="http://tempuri.org/IService1/InsertDocenteResponse")]
        void InsertDocente(AplicacionWeb.Servicios.Colegio.tbl_Docente nuevoDocente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertMateria", ReplyAction="http://tempuri.org/IService1/InsertMateriaResponse")]
        void InsertMateria(AplicacionWeb.Servicios.Colegio.tbl_Materia nuevaMateria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertAula", ReplyAction="http://tempuri.org/IService1/InsertAulaResponse")]
        void InsertAula(AplicacionWeb.Servicios.Colegio.tbl_Aula nuevaAula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertQuimestre", ReplyAction="http://tempuri.org/IService1/InsertQuimestreResponse")]
        void InsertQuimestre(AplicacionWeb.Servicios.Colegio.tbl_Quimestre nuevoQuimestre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertClase", ReplyAction="http://tempuri.org/IService1/InsertClaseResponse")]
        void InsertClase(AplicacionWeb.Servicios.Colegio.tbl_Clase nuevaClase);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertNota", ReplyAction="http://tempuri.org/IService1/InsertNotaResponse")]
        void InsertNota(AplicacionWeb.Servicios.Colegio.tbl_Nota nuevaNota);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertAsistencia", ReplyAction="http://tempuri.org/IService1/InsertAsistenciaResponse")]
        void InsertAsistencia(AplicacionWeb.Servicios.Colegio.tbl_Asistencia nuevaAsitencia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateAlumno", ReplyAction="http://tempuri.org/IService1/UpdateAlumnoResponse")]
        void UpdateAlumno(AplicacionWeb.Servicios.Colegio.tbl_Estudiante actualizarAlumno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateDocente", ReplyAction="http://tempuri.org/IService1/UpdateDocenteResponse")]
        void UpdateDocente(AplicacionWeb.Servicios.Colegio.tbl_Docente actualizarDocente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateMateria", ReplyAction="http://tempuri.org/IService1/UpdateMateriaResponse")]
        void UpdateMateria(AplicacionWeb.Servicios.Colegio.tbl_Materia actualizarMateria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateAula", ReplyAction="http://tempuri.org/IService1/UpdateAulaResponse")]
        void UpdateAula(AplicacionWeb.Servicios.Colegio.tbl_Aula actualizarAula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateQuimestre", ReplyAction="http://tempuri.org/IService1/UpdateQuimestreResponse")]
        void UpdateQuimestre(AplicacionWeb.Servicios.Colegio.tbl_Quimestre actualizarQuimestre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateClase", ReplyAction="http://tempuri.org/IService1/UpdateClaseResponse")]
        void UpdateClase(AplicacionWeb.Servicios.Colegio.tbl_Clase actualizarClase);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateNota", ReplyAction="http://tempuri.org/IService1/UpdateNotaResponse")]
        void UpdateNota(AplicacionWeb.Servicios.Colegio.tbl_Nota actualizarNota);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateAsistencia", ReplyAction="http://tempuri.org/IService1/UpdateAsistenciaResponse")]
        void UpdateAsistencia(AplicacionWeb.Servicios.Colegio.tbl_Asistencia actualizarAsitencia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUser", ReplyAction="http://tempuri.org/IService1/GetUserResponse")]
        AplicacionWeb.Servicios.Colegio.tbl_user[] GetUser();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertUser", ReplyAction="http://tempuri.org/IService1/InsertUserResponse")]
        void InsertUser(AplicacionWeb.Servicios.Colegio.tbl_user nuevoAlumno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateUser", ReplyAction="http://tempuri.org/IService1/UpdateUserResponse")]
        void UpdateUser(AplicacionWeb.Servicios.Colegio.tbl_user actualizarAlumno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteUser", ReplyAction="http://tempuri.org/IService1/DeleteUserResponse")]
        void DeleteUser(AplicacionWeb.Servicios.Colegio.tbl_user eliminarUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Login", ReplyAction="http://tempuri.org/IService1/LoginResponse")]
        string Login(string usuario, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        AplicacionWeb.Servicios.Colegio.CompositeType GetDataUsingDataContract(AplicacionWeb.Servicios.Colegio.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : AplicacionWeb.Servicios.Colegio.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<AplicacionWeb.Servicios.Colegio.IService1>, AplicacionWeb.Servicios.Colegio.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public AplicacionWeb.Servicios.Colegio.tbl_Estudiante[] GetAlumnos() {
            return base.Channel.GetAlumnos();
        }
        
        public AplicacionWeb.Servicios.Colegio.tbl_Docente[] GetDocentes() {
            return base.Channel.GetDocentes();
        }
        
        public AplicacionWeb.Servicios.Colegio.tbl_Quimestre[] GetQuimestres() {
            return base.Channel.GetQuimestres();
        }
        
        public AplicacionWeb.Servicios.Colegio.tbl_Aula[] GetAulas() {
            return base.Channel.GetAulas();
        }
        
        public AplicacionWeb.Servicios.Colegio.tbl_Materia[] GetMaterias() {
            return base.Channel.GetMaterias();
        }
        
        public AplicacionWeb.Servicios.Colegio.tbl_Clase[] GetClases() {
            return base.Channel.GetClases();
        }
        
        public AplicacionWeb.Servicios.Colegio.tbl_Asistencia[] GetAsistencias() {
            return base.Channel.GetAsistencias();
        }
        
        public AplicacionWeb.Servicios.Colegio.tbl_Nota[] GetNotas() {
            return base.Channel.GetNotas();
        }
        
        public AplicacionWeb.Servicios.Colegio.vta_Clase[] GetVistaClases() {
            return base.Channel.GetVistaClases();
        }
        
        public void InsertAlumno(AplicacionWeb.Servicios.Colegio.tbl_Estudiante nuevoAlumno) {
            base.Channel.InsertAlumno(nuevoAlumno);
        }
        
        public void InsertDocente(AplicacionWeb.Servicios.Colegio.tbl_Docente nuevoDocente) {
            base.Channel.InsertDocente(nuevoDocente);
        }
        
        public void InsertMateria(AplicacionWeb.Servicios.Colegio.tbl_Materia nuevaMateria) {
            base.Channel.InsertMateria(nuevaMateria);
        }
        
        public void InsertAula(AplicacionWeb.Servicios.Colegio.tbl_Aula nuevaAula) {
            base.Channel.InsertAula(nuevaAula);
        }
        
        public void InsertQuimestre(AplicacionWeb.Servicios.Colegio.tbl_Quimestre nuevoQuimestre) {
            base.Channel.InsertQuimestre(nuevoQuimestre);
        }
        
        public void InsertClase(AplicacionWeb.Servicios.Colegio.tbl_Clase nuevaClase) {
            base.Channel.InsertClase(nuevaClase);
        }
        
        public void InsertNota(AplicacionWeb.Servicios.Colegio.tbl_Nota nuevaNota) {
            base.Channel.InsertNota(nuevaNota);
        }
        
        public void InsertAsistencia(AplicacionWeb.Servicios.Colegio.tbl_Asistencia nuevaAsitencia) {
            base.Channel.InsertAsistencia(nuevaAsitencia);
        }
        
        public void UpdateAlumno(AplicacionWeb.Servicios.Colegio.tbl_Estudiante actualizarAlumno) {
            base.Channel.UpdateAlumno(actualizarAlumno);
        }
        
        public void UpdateDocente(AplicacionWeb.Servicios.Colegio.tbl_Docente actualizarDocente) {
            base.Channel.UpdateDocente(actualizarDocente);
        }
        
        public void UpdateMateria(AplicacionWeb.Servicios.Colegio.tbl_Materia actualizarMateria) {
            base.Channel.UpdateMateria(actualizarMateria);
        }
        
        public void UpdateAula(AplicacionWeb.Servicios.Colegio.tbl_Aula actualizarAula) {
            base.Channel.UpdateAula(actualizarAula);
        }
        
        public void UpdateQuimestre(AplicacionWeb.Servicios.Colegio.tbl_Quimestre actualizarQuimestre) {
            base.Channel.UpdateQuimestre(actualizarQuimestre);
        }
        
        public void UpdateClase(AplicacionWeb.Servicios.Colegio.tbl_Clase actualizarClase) {
            base.Channel.UpdateClase(actualizarClase);
        }
        
        public void UpdateNota(AplicacionWeb.Servicios.Colegio.tbl_Nota actualizarNota) {
            base.Channel.UpdateNota(actualizarNota);
        }
        
        public void UpdateAsistencia(AplicacionWeb.Servicios.Colegio.tbl_Asistencia actualizarAsitencia) {
            base.Channel.UpdateAsistencia(actualizarAsitencia);
        }
        
        public AplicacionWeb.Servicios.Colegio.tbl_user[] GetUser() {
            return base.Channel.GetUser();
        }
        
        public void InsertUser(AplicacionWeb.Servicios.Colegio.tbl_user nuevoAlumno) {
            base.Channel.InsertUser(nuevoAlumno);
        }
        
        public void UpdateUser(AplicacionWeb.Servicios.Colegio.tbl_user actualizarAlumno) {
            base.Channel.UpdateUser(actualizarAlumno);
        }
        
        public void DeleteUser(AplicacionWeb.Servicios.Colegio.tbl_user eliminarUser) {
            base.Channel.DeleteUser(eliminarUser);
        }
        
        public string Login(string usuario, string password) {
            return base.Channel.Login(usuario, password);
        }
        
        public AplicacionWeb.Servicios.Colegio.CompositeType GetDataUsingDataContract(AplicacionWeb.Servicios.Colegio.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
    }
}
